import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import directus from "../lib/directus";
import styles from "../styles/Home.module.css";
import { Context, PropsWithChildren } from "react";
import { Blog } from "../lib/types/index";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

export type Props = PropsWithChildren<{
  posts: Blog[];
}>;
const Home: NextPage<Props> = ({ posts }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to A demo of Next.js with Directus
        </h1>

        <div className={styles.grid}>
          {posts.map((post) => (
            <Link
              className={styles.card}
              key={post.id}
              href={`/${post.slug}`}
              locale="vi"
            >
              <h2>{post?.translations[0]?.title as string}</h2>
            </Link>
          ))}
        </div>
      </main>
    </div>
  );
};

export default Home;

export const getStaticProps = async () => {
  const res = await directus.items("blog").readByQuery({
    limit: -1,
    fields: ["title", "slug", "id", "image_cover.id", "translations.*"],
    deep: {
      translations: {
        _filter: { languages_id: { _eq: "en-US" } },
      },
    },
  });
  return {
    props: {
      posts: res.data as Blog[],
    },
  };
};
